# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
<<<<<<< HEAD
  secret_key_base: c442c3eb93f7b76ae153151b1ba2b4fc71f767cbd5d7c83179e0eca75a75b59bdb80eb0f5a281241639db41b119b8fc67a6bc18f84e7202a79faafbc3db13e1b

test:
  secret_key_base: e9015dee14e69b050cac9a941191c3a3c76a4d0080fe3fee0459feb67c5b1b35704fc9b1e19b45ab4c1f0d0570ab8e887d5ce47cb5bb3c5a4362e06f9a6bd2bd
=======
  secret_key_base: c8887626145b9a3b0bbc93fdafb12170aa71eb847a579ea0541cb165fe126a47b291d7d90fdcc0dde5e7a868e214feb367a6973eac5108bad828d1ab9889de6d

test:
  secret_key_base: d920208a6704cd4c9e5f18468453f2084ae0112a1309fa0024a3ba09eb8c70e436147b3f71eec4920df9911b56dfc5e1d9856a8a1eccfdc847e3443da776a072
>>>>>>> origin/main

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
